plugins = [
    { id = "nowinandroid.android.feature" },
    { id = "nowinandroid.android.library.compose" },
    { id = "nowinandroid.android.library.jacoco" },
]

android.namespace = "com.google.samples.apps.nowinandroid.feature.settings"

dependencies.implementation = [
    { alias = "libs.androidx.appcompat" },
]