plugins = [
    { id = "nowinandroid.android.application" },
    { id = "nowinandroid.android.application.compose" },
]

dependencies.implementation = [

    { project = ":core:ui"},
    { project = ":core:designsystem"},

    { alias = "libs.androidx.activity.compose" },
]

android.namespace = "com.google.samples.apps.niacatalog"
android.compileSdk = 34

[android.defaultConfig]
applicationId = "com.google.samples.apps.niacatalog"
versionCode = 1
versionName = "0.0.1" # X.Y.Z; X = Major, Y = minor, Z = Patch level
# Custom test runner to set up Hilt dependency graph
testInstrumentationRunner = "com.google.samples.apps.nowinandroid.core.testing.NiaTestRunner"
missingDimensionStrategy = [ "contentType", "demo" ]

[android.defaultConfig.vectorDrawables]
useSupportLibrary = true

[android.buildTypes.debug]
applicationIdSuffix = ".debug"


[android.buildTypes.release]
# Debug key signing is available to everyone.
# To publish on the Play store a private signing key is required, but to allow anyone
# who clones the code to sign and run the release variant, use the debug signing key.
# TODO: Abstract the signing configuration to a separate file to avoid hardcoding this.
signingConfig = "debug"



[android.packaging.resources]
excludes = "/META-INF/{AL2.0,LGPL2.1}"

[android.testOptions.unitTests]
isIncludeAndroidResources = true
