plugins = [
    { id = "nowinandroid.android.library" },
    { id = "nowinandroid.android.library.compose" },
    { id = "nowinandroid.android.hilt" },
]

android.namespace = "com.google.samples.apps.nowinandroid.core.notifications"

dependencies.implementation = [
    { project = ":core:common" },
    { project = ":core:model" },
    { alias = "libs.kotlinx.coroutines.android" },
    { alias = "libs.androidx.browser" },
    { alias = "libs.androidx.compose.runtime" },
    { alias = "libs.androidx.core.ktx" },
    { alias = "libs.firebase.cloud.messaging" },
]