plugins = [
    { id = "nowinandroid.android.feature" },
    { id = "nowinandroid.android.library.compose" },
    { id = "nowinandroid.android.library.jacoco" },
]

android.namespace = "com.google.samples.apps.nowinandroid.feature.bookmarks"

dependencies.implementation = [
    { alias = "libs.androidx.compose.material3.windowSizeClass" },
]