plugins = [
    { id = "nowinandroid.android.library" },
    { id = "nowinandroid.android.library.jacoco" },
    { id = "nowinandroid.android.hilt" },
    { id = "kotlinx-serialization" },
    { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin" },

]

android.namespace = "com.google.samples.apps.nowinandroid.core.network"
android.buildFeatures.buildConfig = true
android.testOptions.unitTests.isIncludeAndroidResources = true

secrets.defaultPropertiesFileName = "secrets.defaults.properties"

dependencies.implementation = [
    { project = ":core:common" },
    { project = ":core:model" },
    { alias = "libs.coil.kt" },
    { alias = "libs.coil.kt.svg" },
    { alias = "libs.kotlinx.coroutines.android" },
    { alias = "libs.kotlinx.datetime" },
    { alias = "libs.kotlinx.serialization.json" },
    { alias = "libs.okhttp.logging" },
    { alias = "libs.retrofit.core" },
    { alias = "libs.retrofit.kotlin.serialization" },
]

dependencies.testImplementation = [
    { project = ":core:testing" },
]