plugins = [
    { id = "nowinandroid.android.library" },
    { id = "nowinandroid.android.hilt" },
]

android.namespace = "com.google.samples.apps.nowinandroid.core.datastore.test"

dependencies.api = [
    { project = ":core:datastore" },
    { alias = "libs.androidx.dataStore.core" },
]
dependencies.implementation = [
    { project = ":core:common" },
    { project = ":core:testing" },
    { alias = "libs.protobuf.kotlin.lite" },
]