plugins = [
    { id = "nowinandroid.android.feature" },
    { id = "nowinandroid.android.library.compose" },
    { id = "nowinandroid.android.library.jacoco" },
]

android.namespace = "com.google.samples.apps.nowinandroid.feature.search"

dependencies.implementation = [
    { project = ":feature:bookmarks" },
    { project = ":feature:foryou" },
    { project = ":feature:interests" },
    { alias = "libs.kotlinx.datetime" },
]