plugins = [
    { id = "nowinandroid.android.feature" },
    { id = "nowinandroid.android.library.compose" },
    { id = "nowinandroid.android.library.jacoco" },
]

android.namespace = "com.google.samples.apps.nowinandroid.feature.foryou"

dependencies.implementation = [
    { alias = "libs.kotlinx.datetime" },
    { alias = "libs.androidx.activity.compose" },
    { alias = "libs.accompanist.permissions" },
]